### ISSUE TITLE
List all the native modules in the devdoc

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/open-source#16]
Currently, there is no comprehensive list of modules and their repository on the devdoc. The only resource available is here:  
https://github.com/PrestaShop/PrestaShop-modules

Let's complete this page of the devdoc with a new section, in order to add the modules that had no equivalent in 1.6:
https://devdocs.prestashop.com/1.7/modules/introduction/

This will be the occasion to check if all modules repositories have a license.md, a readme.md and eventually a contributor.md (prerequisites)

Also, this will help to show the features and all the work being done on 1.7.

Todo:
- [x] Add the new section with missing modules in the devdocs
- [ ] Check if all prerequisites are ok and create relative issues if needed
- [ ] Fix the issues

**Comment by eternoendless** [comment]
I'm currently building the list

**Comment by eternoendless** [comment]
Native modules have been listed here: https://devdocs.prestashop.com/1.7/development/native-modules/#list-of-native-modules

**Comment by ttoine** [comment]
where do we are with license.md and other pre-requisites, @matks ? I know you worked on that but I don't know the status.

**Comment by matks** [comment]
> where do we are with license.md and other pre-requisites, @matks ? I know you worked on that but I don't know the status.

I need some developer tools to be updated and released before: https://github.com/PrestaShopCorp/header-stamp and https://github.com/PrestaShop/php-dev-tools.
When they are updated I can use them to fix all license headers in modules.

**Comment by ttoine** [comment]
thanks for the update !
